---
- name: Deploy systemd service file
  template:
    src: app.service.j2
    dest: /etc/systemd/system/app.service
    mode: '0644'
  notify: Reload systemd

- name: Reload systemd
  systemd:
    daemon_reload: yes

- name: Restart app service
  systemd:
    name: app
    state: restarted
    enabled: yes
